CREATE TABLE "NAVIGATOR"."EDS"  (
		  "OBJECTTYPE" VARCHAR(64) NOT NULL , 
		  "PROPERTY" VARCHAR(64) NOT NULL , 
		  "DISPMODE" VARCHAR(10) , 
		  "REQUIRED" CHAR(1) , 
		  "HIDDEN" CHAR(1) , 
		  "MAXVAL" DOUBLE , 
		  "MINVAL" DOUBLE , 
		  "MAXLEN" INTEGER , 
		  "FORMAT" VARCHAR(64) , 
		  "FORMATDESC" VARCHAR(128) , 
		  "HASDEPENDANT" CHAR(1) )   
		 IN "ICN" ; 
