CREATE TABLE "NAVIGATOR"."EDS_CHOICES"  (
		  "OBJECTTYPE" VARCHAR(64) NOT NULL , 
		  "PROPERTY" VARCHAR(64) NOT NULL , 
		  "LISTDISPNAME" VARCHAR(64) NOT NULL , 
		  "LANG" CHAR(5) NOT NULL , 
		  "DISPNAME" VARCHAR(128) NOT NULL , 
		  "VALUE" VARCHAR(128) NOT NULL , 
		  "DEPON" VARCHAR(64) , 
		  "DEPVALUE" VARCHAR(64) )   
		 IN "ICN" ; 
