<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE WorkFlowDefinition SYSTEM "wfdef4.dtd">
<WorkFlowDefinition ApiVersion="4.0"
Origin="JavaAPI"
	Subject="&quot;Process a Loan with Custom Step Processor&quot;"
	Name="ProcessLoan"
	DisableEmailNotification="false"
	MainAttachment="&quot;loan_document&quot;"
	AuthorTool="Process Designer"
	OtherAuthorTools=""
	versionAgnostic="false"
	validateUsingSchema="true"
	validateFlag="true"
	transferFlag="true">
	<Field
		Name="CustomerName"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="InterestRate"
		ValueExpr="0.0"
		Type="float"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="LoanAmount"
		ValueExpr="0.0"
		Type="float"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="LoanDate"
		ValueExpr="systemtime()"
		Type="time"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="loan_document"
		Description="Loan application"
		ValueExpr="{&quot;||0|0||&quot;}"
		Type="attachment"
		IsArray="true"
		MergeType="AppendNoDup"/>
	<Field
		Name="Region"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="BranchOffice"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Field
		Name="LoanNumber"
		ValueExpr="&quot;&quot;"
		Type="string"
		IsArray="false"
		MergeType="override"/>
	<Map
		Name="Workflow"
		MaxStepId="5" >
		<Step
			StepId="0"
			Name="LaunchStep"
			Description="Enter your loan information and click Launch when you are done."
			XCoordinate="50"
			YCoordinate="50"
			RequestedInterface="Navigator Launch Processor (default)"
			JoinType="none"
			SplitType="or"
			CanReassign="true"
			CanViewStatus="true"
			CanViewHistory="false"
			IgnoreInvalidUsers="false">
			<Parameter
				Name="loan_document"
				Description="Loan application"
				ValueExpr="loan_document"
				Type="attachment"
				IsArray="true"
				Mode="inout"/>
			<Parameter
				Name="LoanAmount"
				ValueExpr="LoanAmount"
				Type="float"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="LoanDate"
				ValueExpr="LoanDate"
				Type="time"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="CustomerName"
				ValueExpr="CustomerName"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Route
				SourceStepId="0"
				DestinationStepId="3"
				RouteId="0">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="100"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="1"/>
				</ModelAttribute>
			</ModelAttributes>
		</Step>
		<Step
			StepId="3"
			Name="VerifyInfo"
			Description="Verify the customer information and fill in the current interest rate and loan date. Click Complete when you are done."
			XCoordinate="151"
			YCoordinate="51"
			RequestedInterface="Step Processor EDU"
			QueueName="LoanOfficer"
			JoinType="or"
			SplitType="or"
			CanReassign="true"
			CanViewStatus="true"
			CanViewHistory="true"
			IgnoreInvalidUsers="false">
			<Parameter
				Name="LoanAmount"
				ValueExpr="LoanAmount"
				Type="float"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="InterestRate"
				ValueExpr="InterestRate"
				Type="float"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="LoanDate"
				ValueExpr="LoanDate"
				Type="time"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="Region"
				ValueExpr="Region"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="LoanNumber"
				ValueExpr="LoanNumber"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="BranchOffice"
				ValueExpr="BranchOffice"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="loan_document"
				Description="Loan application"
				ValueExpr="loan_document"
				Type="attachment"
				IsArray="true"
				Mode="inout"/>
			<Parameter
				Name="CustomerName"
				ValueExpr="CustomerName"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Route
				SourceStepId="3"
				DestinationStepId="5"
				RouteId="1">
				<ModelAttributes>
					<ModelAttribute
						Name="UI_RouteWeight"
						Type="int"
						IsArray="false">
							<Value Val="100"/>
					</ModelAttribute>
				</ModelAttributes>
			</Route>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="2"/>
				</ModelAttribute>
			</ModelAttributes>
		</Step>
		<Step
			StepId="5"
			Name="Process Loan"
			Description="Verify that all loan information is provided and accurate. Click Complete when you are done."
			XCoordinate="255"
			YCoordinate="52"
			RequestedInterface="Navigator Step Processor (default)"
			QueueName="LoanProcessor"
			JoinType="or"
			SplitType="or"
			CanReassign="true"
			CanViewStatus="true"
			CanViewHistory="false"
			IgnoreInvalidUsers="false">
			<Parameter
				Name="loan_document"
				Description="Loan application"
				ValueExpr="loan_document"
				Type="attachment"
				IsArray="true"
				Mode="inout"/>
			<Parameter
				Name="LoanAmount"
				ValueExpr="LoanAmount"
				Type="float"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="InterestRate"
				ValueExpr="InterestRate"
				Type="float"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="LoanDate"
				ValueExpr="LoanDate"
				Type="time"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="CustomerName"
				ValueExpr="CustomerName"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="BranchOffice"
				ValueExpr="BranchOffice"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<Parameter
				Name="LoanNumber"
				ValueExpr="LoanNumber"
				Type="string"
				IsArray="false"
				Mode="in"/>
			<Parameter
				Name="Region"
				ValueExpr="Region"
				Type="string"
				IsArray="false"
				Mode="inout"/>
			<ModelAttributes>
				<ModelAttribute
					Name="UI_StepType"
					Type="int"
					IsArray="false">
						<Value Val="2"/>
				</ModelAttribute>
			</ModelAttributes>
		</Step>
	</Map>
</WorkFlowDefinition>
